server:
  port: 1000
eureka:
  instance:
    hostname: eureka-1000  #主机名
  client:
    register-with-eureka: false #禁止当前注册中心自己注册
    fetch-registry: false # 禁止当前注册中心拉取注册服务订单
    serviceUrl:
      defaultZone: http://127.0.0.1:1000/eureka/
spring:
  application:
    name: AIGOU_EUREKA